version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependabot"
    groups:
      dependencies:
        patterns:
          - "npm"
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependabot"
    groups:
      dependencies:
        patterns:
          - "docker"
