services:
  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    environment:
      NGINX_SERVER_NAME: localhost.omnius-labs.com
      NGINX_PROXY_OPXS_WEB: http://host.docker.internal:3000
      NGINX_PROXY_OPXS_API: http://host.docker.internal:8080
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/ssl/certs/nginx:ro,cached

  certs:
    build:
      context: .
      dockerfile: ./Dockerfile.certs
    command: mkcert -key-file key.pem -cert-file cert.pem omnius-labs.com *.omnius-labs.com
    volumes:
      - ./certs:/app
    profiles:
      - certs
