name: build-and-deploy-dev

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .env.production
        run: |
          echo "NEXT_PUBLIC_API_ORIGIN=https://opxs-dev.omnius-labs.com" >> .env.production
          echo "NEXT_PUBLIC_GOOGLE_OAUTH2_CLIENT_ID=1079744307485-b0ktb5ivtnq3ldssm140ks5v018p2pu2.apps.googleusercontent.com" >> .env.production

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn run export

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy
        run: |
          aws s3 sync --delete --exact-timestamps --region us-east-1 ./out "s3://opxs.v1.dev.web"
