name: build-and-deploy-dev

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .env.production
        run: |
          `cat << EOF > .env.production
          NEXT_PUBLIC_API_ORIGIN=https://opxs-dev.omnius-labs.com
          NEXT_PUBLIC_GOOGLE_OAUTH2_CLIENT_ID=220874586151-ui4d5vkvbngtm0fjqu719o28ef5j3p23.apps.googleusercontent.com
          EOF`

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - name: Check Node.js version
        run: node --version

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy
        run: |
          aws s3 sync --delete --exact-timestamps --region us-east-1 ./out "s3://opxs.v1.dev.web"
          aws cloudfront create-invalidation --region us-east-1 --distribution-id "E6K0SSVZT5NIC" --paths "/*"
